### ISSUE TITLE
`NL = "\r\n"` should base on system rather than hard coding

### ISSUE THREAD

**Issue by xiebruce** [go-xmlfmt/xmlfmt#5]
Just as the title said.

**Comment by AntonioSun** [comment]
Good point. I assumed only Windows users still use XML nowadays. 

Will fix it...
What's your OS BTW?

**Comment by xiebruce** [comment]
My OS is macOS, if you need testing, I'm willing to do the job, cause I'm using this package right now. 

I found that not only the `NL` variable, but this line using `\r` too
```go
p2 := regexp.MustCompile(`\r*\n`).ReplaceAllString(parts[2], " ")
```

For now, I'm replacing all `\r` to empty string to avoid the issue on my system
```go
s = strings.ReplaceAll(s, "\r", "")
```

It's easy to fix the `NL` variable:
```go
NL := "\n"
if runtime.GOOS == "windows" {
    NL = "\r\n"
}
```

But for the RegExp, I don't know how,  waiting for you to fix it, thank you BTW, for sharing this package.

**Comment by AntonioSun** [comment]
I remember why I leave it this way now -- https://github.com/golang/go/issues/28822, and https://github.com/andybalholm/crlf

> It's easy to fix the `NL` variable:
> 
> ```go
> NL := "\n"
> if runtime.GOOS == "windows" {
>     NL = "\r\n"
> }
> ```

thanks for that. So `NL := "\n"` works for macOS makes things much easier. 

The RegExp you don't need to worry, let me fix the NL and you can see...

**Comment by xiebruce** [comment]
> I remember why I leave it this way now -- [golang/go#28822](https://github.com/golang/go/issues/28822),
> 
> > It's easy to fix the `NL` variable:
> > ```go
> > NL := "\n"
> > if runtime.GOOS == "windows" {
> >     NL = "\r\n"
> > }
> > ```
> 
> thanks for that. So `NL := "\n"` works for macOS makes things much easier.
> 
> The RegExp you don't need to worry, let me fix the NL and you can see...

Yes, `\n` works for macOS

**Comment by AntonioSun** [comment]
Under my linux:

```
$ echo '<root><this><is>a</is><test /><message><!-- with comment --><org><cn>Some org-or-other</cn><ph>Wouldnt you like to know</ph></org><contact><fn>Pat</fn><ln>Califia</ln></contact></message></this></root>' | xmlfmt -f | hexdump -C
00000000  0a 3c 72 6f 6f 74 3e 0a  20 20 3c 74 68 69 73 3e  |.<root>.  <this>|
00000010  0a 20 20 20 20 3c 69 73  3e 61 0a 20 20 20 20 3c  |.    <is>a.    <|
00000020  2f 69 73 3e 0a 20 20 20  20 3c 74 65 73 74 20 2f  |/is>.    <test /|
00000030  3e 0a 20 20 20 20 3c 6d  65 73 73 61 67 65 3e 0a  |>.    <message>.|
00000040  20 20 20 20 20 20 3c 21  2d 2d 20 77 69 74 68 20  |      <!-- with |
00000050  63 6f 6d 6d 65 6e 74 20  2d 2d 3e 0a 20 20 20 20  |comment -->.    |
00000060  20 20 3c 6f 72 67 3e 0a  20 20 20 20 20 20 20 20  |  <org>.        |
00000070  3c 63 6e 3e 53 6f 6d 65  20 6f 72 67 2d 6f 72 2d  |<cn>Some org-or-|

```

**Comment by xiebruce** [comment]
I've tried, it works, thank you!
