### ISSUE TITLE
cdata

### ISSUE THREAD

**Issue by FrankIT60** [go-xmlfmt/xmlfmt#8]
Ciao,

I try to format this string but receive a panic.

`"<book><author>Fred</author><text><![CDATA[<message> Welcome to xmlfmt </message>]]></text><isbn>23456</isbn></book>"`

**Comment by AntonioSun** [comment]
Yeah, that day has come -- I was hoping that people would not be dealing with `CDATA`, but the day has _finally_ come.

I meant, the xml `CDATA` is very convoluted to me, and I had no idea how to deal it, even up till today. 

If the RE matching is not complicated enough for you, would you care to send in a PR pls?

**Comment by AntonioSun** [comment]
One idea is to change the `CDATA` to comment before feeding to RE matching, then change it back afterwards. However, I do not know xml CDATA syntax well enough to know if it'll theoretically work.

You can try that kind of data massages on your side before calling xmlfmt if you want, before a proper fix can be done to this lib.

**Comment by FrankIT60** [comment]
Ciao,

I'm sorry but I don't have the skills to help you.

**Comment by AntonioSun** [comment]
Closing as the xml CDATA is too convoluted for me to grasp -- recommend to use external tools to change the CDATA to comment before feeding to xmlfmt.
